# Generated environment configuration file.

channels:
  - conda-forge

dependencies:
  - python=3.9.13
  - pip=22.1.2
  - pip:
    - rpaframework==28.6.3
    - rpaframework-windows==7.5.2
    - webdriver-manager==4.0.2
    - robotframework-seleniumlibrary==6.8.0
    - weasyprint==57
